app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"

oneup_uploader:
    resource: .
    type: uploader

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"