# app/config/security_https.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CHECKINOUT:  ROLE_USER
        ROLE_SUPER_USER:  ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: true
                default_target_path: auto_update
            logout:
                path:   logout
                target: home
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true

    access_control:
        - { path: ^/member/subscribe, role: ROLE_NONE, requires_channel: https }
        - { path: ^/admin/membership, role: ROLE_NONE, requires_channel: https }
        - { path: ^/admin, role: ROLE_ADMIN, requires_channel: https }
        - { path: ^/member, role: ROLE_USER, requires_channel: https }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/reset, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


