# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    knp_menu.renderer.twig.options:
        currentClass: active
        ancestorClass: treeview active
        allow_safe_labels: true

services:

    ## RABBITMQ / QUEUE RELATED ##

    AppBundle\Services\Queue\MailQueueProducer: '@old_sound_rabbit_mq.mail_queue_producer'

    mail_queue.producer:
        class: AppBundle\Services\Queue\MailQueueProducer

    mail_queue.consumer:
        class: AppBundle\Services\Queue\MailQueueConsumer
        arguments:
            - "@logger"
            - "@service.mailer"
            #- "@service.mailer.swiftmailer" # send via SwiftMailer instead

    ## END RABBITMQ ##

    doctrine.dbal.connection_factory:
        class: AppBundle\Account\CustomConnectionFactory

    twigdate.listener.request:
        class: AppBundle\EventListener\TwigDateRequestListener
        arguments:
            - "@twig"
            - "@settings"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    billing:
        class: AppBundle\Services\BillingService
        arguments:
            - '%env(SYMFONY_ENV)%'
            - '@settings'

    billing_listener:
        class: AppBundle\EventListener\BillingListener
        arguments:
            - "@settings"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        arguments:
            - '@service_container'
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        arguments:
            - '@service_container'
        tags:
            - { name: form.type, alias: app_user_profile }

    valid_tag_validator:
        class: AppBundle\Validator\ValidTagValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: valid_tag

    lendengine.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest' # or 'latest'
                region:  "us-west-2" # Oregon
                credentials:
                    key:    "%aws_key%"
                    secret: "%aws_secret%"

    helper.imageresizer:
        class: AppBundle\Helpers\ImageResizer
        arguments: ['@service_container']

    helper.loan_status_label:
        class: AppBundle\Helpers\LoanStatusLabel

    #IMAGE UPLOADING

    uploader.image_namer:
        class: AppBundle\Uploader\Naming\ImageNamer
        arguments:
            - "@settings"

    uploader.file_namer:
        class: AppBundle\Uploader\Naming\FileNamer
        arguments:
            - "@settings"

    uploader.siteimage_namer:
        class: AppBundle\Uploader\Naming\SiteImageNamer
        arguments:
            - "@settings"

    uploader.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@settings"
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    # FOS USER

    service.fos_user_mailer:
        class: AppBundle\Mailer\FOSMailer
        arguments:
            - "@service.email"
            - "@service.tenant"
            - "@twig"
            - "@router"
            - "@settings"

    # If email confirmation is enabled, this is used when email address is confirmed:
    fos_user.registration_complete:
        class: AppBundle\EventListener\RegistrationConfirmListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    # This is used when registration form is submitted:
    fos_user.registration_success:
        class: AppBundle\EventListener\RegistrationSuccessListener
        arguments:
            - "@router"
            - "@service.fos_user_mailer"
            - "@fos_user.util.token_generator"
            - "@settings"
        tags:
            - { name: kernel.event_subscriber }

    fos_user.profile_edit:
        class: AppBundle\EventListener\ProfileEditListener
        tags:
            - { name: kernel.event_subscriber }

    service.tenant:
        class: AppBundle\Services\TenantService
        arguments:
            - "@service_container"
            - "@doctrine.orm.entity_manager"
            - "@billing"
            - "@settings"
            - "@service.loan"
            - '%env(SYMFONY__POSTMARK_API_KEY)%'
            - "@session"

    # Takes data from controllers and services and publishes to the email queue
    service.email:
        class: AppBundle\Services\EmailService
        arguments:
            - "@service.tenant"
            - "@settings"
            - "@old_sound_rabbit_mq.mail_queue_producer"

    # Takes a simple array [from queue] and sends via PostMark
    service.mailer.postmark:
        class: AppBundle\Services\Mailer

    service.mailer.swiftmailer:
        class: AppBundle\Services\MailerSwift  # send via PHPMailer
        arguments:
            $logger : "@logger"
            $transport : "@service.swifttransport"
            $username : "user"
            $password : "password"

    service.swiftmailer:
        class: Swift_Mailer
        arguments:
            - "@service.swifttransport"

    service.swifttransport:
        class: Swift_SmtpTransport
        arguments:
            $host : "localhost"
            $port : 1025
            $encryption : null

    service.mailer:
        class: AppBundle\Services\Mailer

    service.basket:
        class: AppBundle\Services\BasketService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"
            - "@session"
            - "@service.contact"
            - "@serializer"
            - "@security.token_storage"
            - "@service.email"
            - "@service.tenant"
            - "@service.loan"
            - "@translator.default"
            - "@twig"

    settings:
        class: AppBundle\Services\SettingsService
        arguments:
            - "@doctrine.orm.entity_manager"

    service.contact:
        class: AppBundle\Services\Contact\ContactService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    service.membership:
        class: AppBundle\Services\Membership\MembershipService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service.contact"

    service.event:
        class: AppBundle\Services\Event\EventService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"

    service.loan:
        class: AppBundle\Services\Loan\LoanService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"

    service.loan_row:
        class: AppBundle\Services\Loan\LoanRowService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    service.item:
        class: AppBundle\Services\Item\ItemService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    service.inventory:
        class: AppBundle\Services\InventoryService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    service.booking:
        class: AppBundle\Services\Booking\BookingService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"

    service.maintenance:
        class: AppBundle\Services\Maintenance\MaintenanceService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service.inventory"
            - "@service.email"
            - "@twig"
            - "@service.tenant"
            - "@service.contact"

    service.payment:
        class: AppBundle\Services\Payment\PaymentService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"
            - "@service.stripe"
            - "@service.contact"

    service.checkout:
        class: AppBundle\Services\Loan\CheckOutService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@service.contact"
            - "@service.booking"
            - "@service.item"
            - "@settings"

    service.checkin:
        class: AppBundle\Services\Loan\CheckInService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service.contact"
            - "@service.inventory"
            - "@service.waiting_list"
            - "@service.maintenance"
            - "@security.token_storage"
            - "@service.email"
            - "@twig"
            - "@service.tenant"
            - "@settings"

    service.waiting_list:
        class: AppBundle\Services\WaitingList\WaitingListService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
            - "@twig"

    ## APPS ##

    service.apps:
        class: AppBundle\Services\Apps\AppService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"

    service.stripe:
        class: AppBundle\Services\StripeHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@settings"

    service.mailchimp:
        class: AppBundle\Services\Apps\MailchimpService
        arguments:
            - "@service.apps"

    service.twilio:
        class: AppBundle\Services\Apps\TwilioService
        arguments:
            - "@service.apps"
            - "@settings"

    ## REPORT SERVICES

    report.items:
        class: AppBundle\Services\Report\ReportLoanedItems
        arguments:
            - "@doctrine.orm.entity_manager"

    report.all_items:
        class: AppBundle\Services\Report\ReportLoanRows
        arguments:
            - "@doctrine.orm.entity_manager"

    report.non-loaned-items:
        class: AppBundle\Services\Report\ReportNonLoanedItems
        arguments:
            - "@doctrine.orm.entity_manager"

    report.loans:
        class: AppBundle\Services\Report\ReportLoans
        arguments:
            - "@doctrine.orm.entity_manager"

    report.payments:
        class: AppBundle\Services\Report\ReportPayments
        arguments:
            - "@doctrine.orm.entity_manager"

    report.children:
        class: AppBundle\Services\Report\ReportChildren
        arguments:
            - "@doctrine.orm.entity_manager"

    report.site_search:
        class: AppBundle\Services\Report\ReportSiteSearch
        arguments:
            - "@doctrine.orm.entity_manager"

    ## END REPORT SERVICES

    app.cache.clear:
        class: Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand
        calls:
            - [setContainer, ["@service_container"] ]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@service_container"
            - "@security.token_storage"
        tags:
            - { name: knp_menu.menu_builder, method: pagesMenu, alias: pagesMenu }
            - { name: knp_menu.menu_builder, method: pagesMenuStacked, alias: pagesMenuStacked }
            - { name: knp_menu.menu_builder, method: adminMenu, alias: adminMenu }
            - { name: knp_menu.menu_builder, method: settingsMenu, alias: settingsMenu }
            - { name: knp_menu.menu_builder, method: accountMenu, alias: accountMenu }

    service.site_nav:
        class: \AppBundle\Services\SiteNav
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.authorization_checker"
            - "@settings"
            - "@translator.default"
            - "@router"
            - "@request_stack"

    ## SCHEDULED ACTIONS

    service.schedule_loan_reminders:
        class: AppBundle\Services\Schedule\EmailLoanReminders
        arguments:
            - "@twig"
            - "@service_container"
            - "@settings"
            - "@service.contact"
            - "@service.email"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    service.schedule_overdue_loans:
        class: AppBundle\Services\Schedule\EmailOverdueLoans
        arguments:
            - "@twig"
            - "@service_container"
            - "@settings"
            - "@service.contact"
            - "@service.email"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    service.schedule_reservation_reminders:
        class: AppBundle\Services\Schedule\EmailReservationReminders
        arguments:
            - "@twig"
            - "@service_container"
            - "@settings"
            - "@service.contact"
            - "@service.email"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    service.schedule_memberships:
        class: AppBundle\Services\Schedule\ExpireMemberships
        arguments:
            - "@twig"
            - "@service_container"
            - "@settings"
            - "@service.contact"
            - "@service.email"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    service.schedule_maintenance:
        class: AppBundle\Services\Schedule\UpdateMaintenance
        arguments:
            - "@twig"
            - "@service_container"
            - "@settings"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    ## END SCHEDULED ACTIONS

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%', "@service.tenant"]
        tags:
            - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }